const products=[
{id:1,name:'Elegant Rose Midi Dress',cat:'Women',price:28500,old:36500,rating:5,desc:'Soft luxury dress for events and dinner outings.',img:'https://images.unsplash.com/photo-1539008835657-9e8e9680c956?auto=format&fit=crop&w=700&q=80'},
{id:2,name:'Executive Blue Office Suit',cat:'Women',price:62000,old:78000,rating:5,desc:'Corporate suit for meetings, work, and presentations.',img:'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=700&q=80'},
{id:3,name:'Classic Men White Shirt',cat:'Men',price:18500,old:24000,rating:4,desc:'Clean formal shirt for office and smart casual looks.',img:'https://images.unsplash.com/photo-1620012253295-c15cc3e65df4?auto=format&fit=crop&w=700&q=80'},
{id:4,name:'Premium Native Set',cat:'Men',price:48000,old:59000,rating:5,desc:'Stylish traditional outfit for occasions and events.',img:'https://images.unsplash.com/photo-1603252109303-2751441dd157?auto=format&fit=crop&w=700&q=80'},
{id:5,name:'Little Princess Party Dress',cat:'Kids',price:21000,old:28000,rating:5,desc:'Beautiful children’s dress for birthdays and outings.',img:'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?auto=format&fit=crop&w=700&q=80'},
{id:6,name:'Urban White Sneakers',cat:'Shoes',price:35000,old:45000,rating:4,desc:'Comfortable sneakers for casual and weekend style.',img:'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=700&q=80'},
{id:7,name:'Luxury Black Heels',cat:'Shoes',price:39500,old:51000,rating:5,desc:'Elegant heels for office, dinner, and special events.',img:'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=700&q=80'},
{id:8,name:'Premium Leather Handbag',cat:'Bags',price:52000,old:66000,rating:5,desc:'Luxury handbag with spacious everyday storage.',img:'https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&w=700&q=80'},
{id:9,name:'Gold Minimal Watch',cat:'Accessories',price:44000,old:57000,rating:5,desc:'Elegant fashion watch for premium daily styling.',img:'https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=700&q=80'},
{id:10,name:'Silk Pattern Scarf',cat:'Accessories',price:12500,old:18000,rating:4,desc:'Soft scarf to complete casual and formal outfits.',img:'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?auto=format&fit=crop&w=700&q=80'},
{id:11,name:'Slim Fit Blue Jeans',cat:'Women',price:26500,old:33000,rating:4,desc:'Comfort stretch jeans for everyday confidence.',img:'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=700&q=80'},
{id:12,name:'Men Denim Jacket',cat:'Men',price:42000,old:54000,rating:5,desc:'Strong denim jacket for modern street fashion.',img:'https://images.unsplash.com/photo-1551537482-f2075a1d41f2?auto=format&fit=crop&w=700&q=80'},
{id:13,name:'Corporate Pencil Dress',cat:'Women',price:31500,old:42000,rating:5,desc:'Smart office dress for a polished professional look.',img:'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=700&q=80'},
{id:14,name:'Casual Cotton Top',cat:'Women',price:16500,old:22000,rating:4,desc:'Light everyday top for relaxed and stylish outfits.',img:'https://images.unsplash.com/photo-1503341455253-b2e723bb3dbb?auto=format&fit=crop&w=700&q=80'},
{id:15,name:'Luxury Evening Gown',cat:'Women',price:85000,old:105000,rating:5,desc:'Statement gown for weddings, dinners, and occasions.',img:'https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=700&q=80'},
{id:16,name:'Men Premium Polo Shirt',cat:'Men',price:22500,old:29000,rating:4,desc:'Smart polo shirt for neat casual dressing.',img:'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=700&q=80'},
{id:17,name:'Kids Denim Set',cat:'Kids',price:24500,old:31500,rating:4,desc:'Comfortable denim outfit set for children.',img:'https://images.unsplash.com/photo-1522771930-78848d9293e8?auto=format&fit=crop&w=700&q=80'},
{id:18,name:'Brown Leather Loafers',cat:'Shoes',price:46500,old:58000,rating:5,desc:'Premium loafers for business and formal wear.',img:'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?auto=format&fit=crop&w=700&q=80'},
{id:19,name:'Mini Crossbody Bag',cat:'Bags',price:27500,old:36000,rating:4,desc:'Cute crossbody bag for errands and outings.',img:'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=700&q=80'},
{id:20,name:'Pearl Necklace Set',cat:'Accessories',price:19500,old:26000,rating:5,desc:'Beautiful necklace set for elegant finishing.',img:'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=700&q=80'},
{id:21,name:'Floral Summer Dress',cat:'Women',price:24500,old:32000,rating:4,desc:'Bright floral style for warm days and brunch.',img:'https://images.unsplash.com/photo-1585487000160-6ebcfceb0d03?auto=format&fit=crop&w=700&q=80'},
{id:22,name:'Men Black Blazer',cat:'Men',price:68000,old:85000,rating:5,desc:'Sharp blazer for business and premium events.',img:'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=700&q=80'},
{id:23,name:'Kids Sport Sneakers',cat:'Kids',price:22000,old:28500,rating:4,desc:'Durable kids sneakers for play and school outings.',img:'https://images.unsplash.com/photo-1514989940723-e8e51635b782?auto=format&fit=crop&w=700&q=80'},
{id:24,name:'Ladies Gold Sandals',cat:'Shoes',price:29500,old:39000,rating:5,desc:'Chic sandals for classy casual fashion.',img:'https://images.unsplash.com/photo-1562273138-f46be4ebdf33?auto=format&fit=crop&w=700&q=80'},
{id:25,name:'Structured Tote Bag',cat:'Bags',price:57500,old:72000,rating:5,desc:'Work-ready tote bag with premium structure.',img:'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=700&q=80'},
{id:26,name:'Designer Sunglasses',cat:'Accessories',price:18000,old:25000,rating:4,desc:'Stylish sunglasses for luxury street style.',img:'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=700&q=80'},
{id:27,name:'Women Knit Cardigan',cat:'Women',price:33500,old:42000,rating:4,desc:'Soft cardigan for layered fashion comfort.',img:'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?auto=format&fit=crop&w=700&q=80'},
{id:28,name:'Men Casual Chinos',cat:'Men',price:28500,old:36000,rating:4,desc:'Versatile chinos for smart and casual styling.',img:'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&w=700&q=80'},
{id:29,name:'Girls Casual Outfit',cat:'Kids',price:19500,old:25500,rating:5,desc:'Adorable daily outfit for girls and toddlers.',img:'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?auto=format&fit=crop&w=700&q=80'},
{id:30,name:'Premium Travel Duffel Bag',cat:'Bags',price:64000,old:81000,rating:5,desc:'Durable fashion travel bag for weekend trips.',img:'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=700&q=80'}
];
const money=v=>'₦'+v.toLocaleString('en-NG');let currentFilter='All';let cart=JSON.parse(localStorage.getItem('ladybird-cart')||'[]');
function saveCart(){localStorage.setItem('ladybird-cart',JSON.stringify(cart))}function getById(id){return document.getElementById(id)}
function layout(active='home'){document.body.insertAdjacentHTML('afterbegin',`<div class="announcement">✨ <span>Ladybird Global Collections</span> — Premium fashion, trusted delivery, client-ready shopping experience.</div><div class="nav-wrap"><div class="container"><nav><a href="/" class="logo"><span class="logo-mark">LB</span><span>Ladybird Global<br/>Collections</span></a><div class="nav-links" id="navLinks"><a class="${active==='home'?'active':''}" href="/">Home</a><a class="${active==='shop'?'active':''}" href="/shop/">Shop</a><a class="${active==='collections'?'active':''}" href="/collections/">Collections</a><a class="${active==='about'?'active':''}" href="/about/">About</a><a class="${active==='reviews'?'active':''}" href="/reviews/">Reviews</a><a class="${active==='contact'?'active':''}" href="/contact/">Contact</a></div><div class="nav-actions"><button class="cart-btn" onclick="openCart()">🛒 Cart <span class="cart-count" id="cartCount">0</span></button><button class="menu-btn" onclick="toggleMenu()">☰</button><a class="btn" href="/shop/">Shop Now</a></div></nav></div></div>`);document.body.insertAdjacentHTML('beforeend',`<footer><div class="container"><div class="footer-grid"><div><h3>Ladybird Global Collections</h3><p>A professional multi-page fashion marketplace for clothes, shoes, bags, and accessories.</p></div><div><h4>Quick Links</h4><a href="/">Home</a><a href="/shop/">Shop</a><a href="/collections/">Collections</a><a href="/about/">About</a></div><div><h4>Categories</h4><a href="/shop/">Women</a><a href="/shop/">Men</a><a href="/shop/">Kids</a><a href="/shop/">Shoes & Bags</a></div><div><h4>Customer Service</h4><a href="/contact/">Contact</a><a href="/cart/">Cart Checkout</a><a href="#">Returns</a><a href="#">Instagram | Facebook</a></div></div><div class="copyright">© <span id="year"></span> Ladybird Global Collections. All rights reserved.</div></div></footer><div class="cart-overlay" id="cartOverlay" onclick="closeCart()"></div><aside class="cart-drawer" id="cartDrawer"><div class="cart-head"><h3>Your Shopping Cart</h3><button class="close-cart" onclick="closeCart()">×</button></div><div class="cart-items" id="cartItems"></div><div class="cart-bottom"><div class="total-row"><span>Total</span><span id="cartTotal">₦0</span></div><form class="checkout" onsubmit="payNow(event)"><input required placeholder="Customer full name"><input required placeholder="Phone number"><input required placeholder="Delivery address"><select required><option value="">Select payment method</option><option>Pay with Card</option><option>Bank Transfer</option><option>Pay on Delivery</option></select><button class="btn" type="submit">Pay Now</button><a class="btn secondary" href="/cart/">Open Full Checkout</a></form></div></aside><div class="toast" id="toast"></div>`);getById('year').textContent=new Date().getFullYear();updateCart()}
function toggleMenu(){getById('navLinks').classList.toggle('show')}function openCart(){getById('cartDrawer').classList.add('show');getById('cartOverlay').classList.add('show')}function closeCart(){getById('cartDrawer').classList.remove('show');getById('cartOverlay').classList.remove('show')}function showToast(msg){const t=getById('toast');if(!t)return; t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3200)}
function addToCart(id,open=true){const p=products.find(x=>x.id===id),e=cart.find(x=>x.id===id);e?e.qty++:cart.push({...p,qty:1});saveCart();updateCart();showToast(p.name+' added to cart');if(open)openCart()}
function changeQty(id,amount){const i=cart.find(x=>x.id===id);if(!i)return;i.qty+=amount;if(i.qty<=0)cart=cart.filter(x=>x.id!==id);saveCart();updateCart();if(getById('cartPageItems'))renderCartPage()}
function removeItem(id){cart=cart.filter(x=>x.id!==id);saveCart();updateCart();showToast('Item removed');if(getById('cartPageItems'))renderCartPage()}
function updateCart(){const count=cart.reduce((s,i)=>s+i.qty,0);if(getById('cartCount'))getById('cartCount').textContent=count;if(getById('cartItems')){getById('cartItems').innerHTML=cart.length?cart.map(item=>`<div class="cart-item"><img src="${item.img}" alt="${item.name}"><div><h4>${item.name}</h4><div class="cart-price">${money(item.price)}</div><div class="qty"><button onclick="changeQty(${item.id},-1)">−</button><strong>${item.qty}</strong><button onclick="changeQty(${item.id},1)">+</button></div></div><button class="remove" onclick="removeItem(${item.id})">×</button></div>`).join(''):'<div class="empty">Your cart is empty. Start shopping from the marketplace.</div>'}const total=cart.reduce((s,i)=>s+i.price*i.qty,0);if(getById('cartTotal'))getById('cartTotal').textContent=money(total);if(getById('cartPageTotal'))getById('cartPageTotal').textContent=money(total)}
function payNow(e){e.preventDefault();if(cart.length===0){showToast('Please add at least one product to cart first.');return}cart=[];saveCart();updateCart();if(getById('cartPageItems'))renderCartPage();closeCart();showToast('Thank you for shopping with Ladybird Global Collections. Your order has been received.');e.target.reset()}
function renderProducts(limit){const grid=getById('productGrid');if(!grid)return;const q=(getById('searchInput')?.value||'').toLowerCase().trim();let list=products.filter(p=>(currentFilter==='All'||p.cat===currentFilter)&&(!q||`${p.name} ${p.cat} ${p.desc}`.toLowerCase().includes(q)));if(limit)list=list.slice(0,limit);grid.innerHTML=list.map(p=>`<article class="product"><div class="product-img"><img src="${p.img}" alt="${p.name}"><span class="badge">${p.cat}</span></div><div class="product-body"><div class="product-top"><h3>${p.name}</h3><div class="stars">${'★'.repeat(p.rating)}${'☆'.repeat(5-p.rating)}</div></div><p>${p.desc}</p><div class="price-row"><span class="price">${money(p.price)}</span><span class="old-price">${money(p.old)}</span></div><div class="product-actions"><button class="mini-btn light" onclick="addToCart(${p.id},false)">Add to Cart</button><button class="mini-btn" onclick="addToCart(${p.id},true)">Buy Now</button></div></div></article>`).join('')||'<div class="empty" style="grid-column:1/-1">No product found.</div>'}
function renderFilters(){const el=getById('filters');if(!el)return;el.innerHTML=['All','Women','Men','Kids','Shoes','Bags','Accessories'].map(f=>`<button class="filter-btn ${f===currentFilter?'active':''}" onclick="currentFilter='${f}';renderFilters();renderProducts();">${f}</button>`).join('')}function bindShop(){renderFilters();renderProducts();getById('searchInput')?.addEventListener('input',()=>renderProducts())}
function renderCartPage(){const el=getById('cartPageItems');if(!el)return;el.innerHTML=cart.length?cart.map(item=>`<div class="cart-item" style="grid-template-columns:96px 1fr auto"><img style="width:96px;height:96px" src="${item.img}" alt="${item.name}"><div><h4>${item.name}</h4><div class="cart-price">${money(item.price)} x ${item.qty}</div><div class="qty"><button onclick="changeQty(${item.id},-1)">−</button><strong>${item.qty}</strong><button onclick="changeQty(${item.id},1)">+</button></div></div><button class="remove" onclick="removeItem(${item.id})">×</button></div>`).join(''):'<div class="empty">Your cart is empty. Go to the shop page and add products.</div>';updateCart()}
function submitSuccess(e,msg){e.preventDefault();showToast(msg);e.target.reset()}
